version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [release, pr_build]
    default: pr_build
  dry_run:
    type: boolean
    default: true
    description: "Run in dry run mode?"
  maven_profile_id:
    type: string
    default: "gravitee-dry-run"
    description: "Maven ID of the Maven profile to use for a dry run ?"
  secrethub_org:
    type: string
    default: "gravitee-lab"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.4

jobs:
  empty_job:
    docker:
     - image: alpine
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: "This is a dummy empty job (isn't it ?)"
          command: echo "No task is executed."

  mvn_release_job:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    steps:
      - checkout
      - secrethub/install
      # - docker/install-docker-compose
      - gravitee/mvn_prepare_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      - gravitee/mvn_test_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      - gravitee/mvn_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      # - gravitee/git_release:
          # dry_run: << pipeline.parameters.dry_run >>
          # maven_container_image_tag: << pipeline.parameters.maven_container_image_tag >>
          # maven_profile_id: << pipeline.parameters.maven_profile_id>>
          # secrethub_org: << pipeline.parameters.secrethub_org >>
          # secrethub_repo: << pipeline.parameters.secrethub_repo >>
      - run:
          name: "Ok, where are the zip and npm packages ?"
          command: ls -allh .
  git_release_job:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    steps:
      - checkout
      - secrethub/install
      - docker/install-docker-compose
      - gravitee/mvn_prepare_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      # - gravitee/mvn_test_release:
          # dry_run: << pipeline.parameters.dry_run >>
          # maven_container_image_tag: stable-latest
          # maven_profile_id: << pipeline.parameters.maven_profile_id>>
          # secrethub_org: << pipeline.parameters.secrethub_org >>
          # secrethub_repo: << pipeline.parameters.secrethub_repo >>
      # - gravitee/mvn_release:
          # dry_run: << pipeline.parameters.dry_run >>
          # maven_container_image_tag: stable-latest
          # maven_profile_id: << pipeline.parameters.maven_profile_id>>
          # secrethub_org: << pipeline.parameters.secrethub_org >>
          # secrethub_repo: << pipeline.parameters.secrethub_repo >>
      - gravitee/git_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: << pipeline.parameters.maven_container_image_tag >>
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
  container_build:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    steps:
      - checkout
      - secrethub/install
      - docker/install-docker-compose
      - run:
          name: "There I'll docker build the container image'"
          command: ls -allh .

workflows:
  version: 2.1
  pull_requests:
    when:
      equal: [ pr_build, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/pr-build:
          context: cicd-orchestrator
  mvn_release:
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - not: << pipeline.parameters.dry_run >>
    jobs:
      - gravitee/release:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
          maven_profile_id: << pipeline.parameters.maven_profile_id >>
  release_dry_run:
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - << pipeline.parameters.dry_run >>
    jobs:
      - gravitee/release:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
          maven_profile_id: << pipeline.parameters.maven_profile_id >>
